<?php


$form->setAttribute('action', $this->url('auth_user', array('action' => 'login')));
$form->prepare();

echo $this->form()->openTag($form) ;

echo $this->formLabel($form->get('username'));
echo $this->formInput($form->get('username'));
echo $this->formElementErrors($form->get('username'));
echo $this->formLabel($form->get('password'));
echo $this->formInput($form->get('password'));
echo $this->formElementErrors($form->get('password'));

echo $this->formInput($form->get('submit'));
echo $this->form()->closeTag($form) ;